swagger: '2.0'
info:
  title: Proof of Concept - API Doc
  description: |
    This API documentation provides a comprehensive overview of the endpoints available.

    **Endpoints**: The API offers endpoints for reading and writing system information, sending CAN frames, and managing ECU versions.

    **Usage**: Each endpoint is detailed with request parameters, response formats, and example data to guide users in integrating with the API effectively.

    Please review the endpoint descriptions and examples to understand the available functionality and how to interact with the API.
  version: 1.0.0

basePath: '/api'


paths:
  /request_ids:
    get:
      summary: Retrieves ECU and MCU IDs
      description: Retrieves ECU and MCU IDs.
      responses:
        '200':
          description: ECU and MCU IDs
          schema:
            type: object
            properties:
              ecu_ids:
                type: array
                items:
                  type: string
              mcu_id:
                type: string
              status:
                type: string
              time_stamp:
                type: string
            example:
              ecu_ids: ["11", "00", "00", "00"]
              mcu_id: "10"
              status: "Success"
              time_stamp: "2024-08-02T10:12:26.308454"

  /send_frame:
    post:
      summary: Sends a CAN frame with the specified ID and data
      description: Sends a CAN frame with the specified ID and data.
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              can_id:
                type: string
              can_data:
                type: string
            example:
              can_id: "0xFA10"
              can_data: "0x04,0x27,0x02,0x0E,0x37"
      responses:
        '200':
          description: Status of the CAN frame send
          schema:
            type: object
            properties:
              can_id:
                type: string
              can_data:
                type: array
                items:
                  type: string
              auth_status:
                type: string
              error_text:
                type: string
              retry_timeout_ms:
                type: integer
            example:
              can_id: "0xFA10"
              can_data: ["0x04", "0x67", "0x01", "0x00", "0x00"]
              auth_status: "success"
              error_text: "Specific error message if any"
              retry_timeout_ms: 5000

  /read_info_battery:
    get:
      summary: Reads information related to the battery
      description: Reads information related to the battery.
      responses:
        '200':
          description: Battery information
          schema:
            type: object
            properties:
              battery_level:
                type: string
              voltage:
                type: string
              battery_state_of_charge:
                type: string
              percentage:
                type: string
              life_cycle:
                type: string
              fully_charged:
                type: string
              serial_number:
                type: string
              range_battery:
                type: string
              charging_time:
                type: string
              device_consumption:
                type: string
              time_stamp:
                type: string
            example:
              battery_level: "75"
              voltage: "12V"
              battery_state_of_charge: "Charging"
              percentage: "80.00%"
              life_cycle: "NA"
              fully_charged: "NA"
              serial_number: "NA"
              range_battery: "NA"
              charging_time: "NA"
              device_consumption: "NA"
              time_stamp: "2024-07-26T12:34:56.789Z"

  /read_info_engine:
    get:
      summary: Reads information related to the engine
      description: Reads information related to the engine.
      responses:
        '200':
          description: Engine information
          schema:
            type: object
            properties:
              current_speed:
                type: string
              engine_state:
                type: string
              fuel_consumption:
                type: string
              fuel_used:
                type: string
              power_output:
                type: string
              serial_number:
                type: string
              state_of_running:
                type: string
              torque:
                type: string
              weight:
                type: string
            example:
              current_speed: "26"
              engine_state: "27"
              fuel_consumption: "22"
              fuel_used: "24"
              power_output: "21"
              serial_number: "28"
              state_of_running: "25"
              torque: "23"
              weight: "22"

  /write_info_battery:
    post:
      summary: Writes information to the battery module
      description: Writes information to the battery module.
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              battery_level:
                type: string
              battery_state_of_charge:
                type: string
              percentage:
                type: string
              voltage:
                type: string
            example:
              battery_level: "20"
              battery_state_of_charge: "3"
              percentage: "30"
              voltage: "10"
      responses:
        '200':
          description: Battery write status
          schema:
            type: object
            properties:
              No_of_errors:
                type: integer
              status:
                type: string
              time_stamp:
                type: string
            example:
              No_of_errors: 0
              status: "success"
              time_stamp: "2024-08-01T11:58:34.561014"

  /write_info_doors:
    post:
      summary: Writes information to the doors module
      description: Writes information to the doors module.
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              door:
                type: integer
              serial_number:
                type: integer
              lighter_voltage:
                type: integer
              light_state:
                type: integer
              belt:
                type: integer
              windows_closed:
                type: integer
            example:
              door: 1
              serial_number: 12345
              lighter_voltage: 12
              light_state: 1
              belt: 0
              windows_closed: 1
      responses:
        '200':
          description: Door write status
          schema:
            type: object
            properties:
              No_of_errors:
                type: integer
              status:
                type: string
              time_stamp:
                type: string
            example:
              No_of_errors: 0
              status: "success"
              time_stamp: "2024-08-01T11:58:34.561014"

  /read_info_doors:
    get:
      summary: Reads information related to the doors module
      description: Reads information related to the doors module.
      responses:
        '200':
          description: Doors information
          schema:
            type: object
            properties:
              door:
                type: integer
              serial_number:
                type: integer
              lighter_voltage:
                type: integer
              light_state:
                type: integer
              belt:
                type: integer
              windows_closed:
                type: integer
            example:
              door: 1
              serial_number: 12345
              lighter_voltage: 12
              light_state: 1
              belt: 0
              windows_closed: 1

  /drive_update_data:
    get:
      summary: Retrieves the structure of available software versions in the drive
      description: Retrieves the structure of available software versions in the drive.
      responses:
        '200':
          description: Drive update data
          schema:
            type: object
            properties:
              children:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    type:
                      type: string
                    children:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                          size:
                            type: string
                          sw_version:
                            type: string
                          type:
                            type: string
            example:
              children: 
                - id: "1zyG1zz6fo2w1-NndQ3KES4foZ2L98lrI"
                  name: "release"
                  type: "folder"
                - id: "1QkgBWPEaKg5bnOU0eXjPOEcz6lqNCG-N"
                  name: "ECU_BATTERY_SW_VERSIONS"
                  type: "folder"
                  children:
                    - id: "1Wq3GQUMraXaukpe5T-SBN0_3uly2TaQW"
                      name: "ECU_BATTERY_SW_VERSION_1.zip"
                      size: "4211322"
                      sw_version: "1"
                      type: "zip"
                - id: "1aGo68MWCYBxMVSPd0-jZ4cBGICGdMRxp"
                  name: "MCU_SW_VERSIONS"
                  type: "folder"
                  children:
                    - id: "143rz1vZ6AdFclaVUV3hPRG7tIyJ-Wvr0"
                      name: "MCU_SW_VERSION_2.2.zip"
                      size: "4302707"
                      sw_version: "2.2"
                      type: "zip"

  /update_to_version:
    post:
      summary: Updates the software version of a specific ECU
      description: Updates the software version of a specific ECU.
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              update_file_id:
                type: string
              update_file_size:
                type: integer
              update_file_version:
                type: string
              update_file_type:
                type: string
              module_id:
                type: integer
            example:
              update_file_id: "7rer84crfsfs872455qad"
              update_file_size: 353532
              update_file_version: "1.1"
              update_file_type: "zip"
              module_id: 11
      responses:
        '200':
          description: Update status
          schema:
            type: object
            properties:
              status_download:
                type: string
              errors:
                type: integer
              time_stamp:
                type: string
            example:
              status_download: "downloaded"
              errors: 0
              time_stamp: "2024-07-26T12:34:56.789Z"
