# Constants
API_ID = 0xFA
MCU = 0
ECU_BATTERY = 1
ECU_ENGINE = 2
ECU_DOORS = 3
ECU_HVAC = 4
# Identifiers
IDENTIFIER_VERSION_SOFTWARE_MCU = 0x1010
IDENTIFIER_VEHICLE_IDENTIFICATION_NUMBER_VIN = 0xF190
IDENTIFIER_ECU_SERIAL_NUMBER = 0xF17F
IDENTIFIER_SYSTEM_SUPPLIER_ECU_HARDWARE_NUMBER = 0xF18C
IDENTIFIER_SYSTEM_SUPPLIER_ECU_SOFTWARE_NUMBER = 0xF1A0
IDENTIFIER_SYSTEM_NAME_OR_ENGINE_TYPE = 0xF187
IDENTIFIER_SYSTEM_SUPPLIER_ECU_SOFTWARE_VERSION_NUMBER = 0xF1A2
IDENTIFIER_SYSTEM_SUPPLIER_ECU_HARDWARE_VERSION_NUMBER = 0xF1A1
IDENTIFIER_SYSTEM_SUPPLIER_ECU_MANUFACTURING_DATE = 0xF1A4
IDENTIFIER_SYSTEM_SUPPLIER_ECU_CODING_CONFIGURATION_PART_NUMBER = 0xF1A5
IDENTIFIER_SYSTEM_CALIBRATION_IDENTIFICATION_NUMBER = 0xF1A8
IDENTIFIER_SYSTEM_CALIBRATION_VERIFICATION_NUMBER_CVN = 0xF1A9
IDENTIFIER_SYSTEM_ECU_BOOT_SOFTWARE_IDENTIFICATION_NUMBER = 0xF1AA
IDENTIFIER_SYSTEM_ECU_APPLICATION_SOFTWARE_IDENTIFICATION_NUMBER = 0xF1AB
IDENTIFIER_SYSTEM_ECU_DATA_SET_IDENTIFICATION_NUMBER = 0xF1AC
IDENTIFIER_SYSTEM_ECU_FLASH_SOFTWARE_VERSION_NUMBER = 0xF1AD
IDENTIFIER_MASS_AIR_FLOW_MAF_SENSOR = 0x0134
# Battery
IDENTIFIER_BATTERY_ENERGY_LEVEL = 0x01A0
IDENTIFIER_BATTERY_VOLTAGE = 0x01B0
IDENTIFIER_BATTERY_PERCENTAGE = 0x01C0
IDENTIFIER_BATTERY_STATE_OF_CHARGE = 0x01D0
IDENTIFIER_BATTERY_TEMPERATURE = 0x01E0
IDENTIFIER_BATTERY_LIFE_CYCLE = 0x01F0
IDENTIFIER_BATTERY_FULLY_CHARGED = 0x02A0
IDENTIFIER_BATTERY_RANGE = 0x02B0
IDENTIFIER_BATTERY_CHARGING_TIME = 0x02C0
IDENTIFIER_DEVICE_CONSUMPTION = 0x02D0
# Doors
# IDENTIFIER_DOOR = 0x2001
# IDENTIFIER_DOOR_SERIALNUMBER = 0x2002
# IDENTIFIER_LIGHTER_VOLTAGE = 0x210D
# IDENTIFIER_LIGHT_STATE = 0x221E
# IDENTIFIER_BELT_STATE = 0x21C1
# IDENTIFIER_WINDOWS_CLOSED = 0x230F
IDENTIFIER_DOOR_STATUS = 0x03A0
IDENTIFIER_PASSENGER_DOOR_STATUS = 0x03B0
IDENTIFIER_DRIVER_DOOR_STATUS = 0x03C0
IDENTIFIER_PASSENGER_DOOR_LOCKED_STATUS = 0x03D0
IDENTIFIER_AJAR_STATUS = 0x03E0
# Engine
# IDENTIFIER_ENGINE_POWER_OUTPUT = 0x0141
# IDENTIFIER_ENGINE_WEIGHT = 0x0142
# IDENTIFIER_ENGINE_FUEL_CONSUMPTION = 0x0143
# IDENTIFIER_ENGINE_TORQUE = 0x0144
# IDENTIFIER_ENGINE_FUEL_USED = 0x0145
# IDENTIFIER_ENGINE_STATE_OF_RUNNING = 0x0146
# IDENTIFIER_ENGINE_CURRENT_SPEED = 0x0147
# IDENTIFIER_ENGINE_STATE = 0x0148
# IDENTIFIER_ENGINE_SERIAL_NUMBER = 0x0149
IDENTIFIER_ENGINE_RPM = 0x0100
IDENTIFIER_ENGINE_COOLANT_TEMPERATURE = 0x010C
IDENTIFIER_THROTTLE_POSITION = 0x0110
IDENTIFIER_VEHICLE_SPEED = 0x0114
IDENTIFIER_ENGINE_LOAD = 0x011C
IDENTIFIER_FUEL_LEVEL = 0x0120
IDENTIFIER_OIL_TEMPERATURE = 0x0124
IDENTIFIER_FUEL_PRESSURE = 0x012C
IDENTIFIER_ENGINE_AIR_INTAKE = 0x0130

#HVAC
IDENTIFIER_MASS_AIR_FLOW = 0x0134  
IDENTIFIER_AMBIENT_AIR_TEMPERATURE = 0x0140
IDENTIFIER_CABIN_TEMPERATURE = 0x04A0  
IDENTIFIER_CABIN_TEMPERATURE_DRIVER_SET = 0x04B0
IDENTIFIER_FAN_SPEED = 0x04C0 
IDENTIFIER_HVAC_MODES = 0x04D0 


data_identifiers = {
        "MCU_Identifiers": {
            "software_version": hex(IDENTIFIER_VERSION_SOFTWARE_MCU),
            "vin": hex(IDENTIFIER_VEHICLE_IDENTIFICATION_NUMBER_VIN),
            "ecu_serial_number": hex(IDENTIFIER_ECU_SERIAL_NUMBER),
            "ecu_hardware_number": hex(IDENTIFIER_SYSTEM_SUPPLIER_ECU_HARDWARE_NUMBER),
            "ecu_software_number": hex(IDENTIFIER_SYSTEM_SUPPLIER_ECU_SOFTWARE_NUMBER),
            "engine_type": hex(IDENTIFIER_SYSTEM_NAME_OR_ENGINE_TYPE),
            "ecu_software_version_number": hex(IDENTIFIER_SYSTEM_SUPPLIER_ECU_SOFTWARE_VERSION_NUMBER),
            "ecu_hardware_version_number": hex(IDENTIFIER_SYSTEM_SUPPLIER_ECU_HARDWARE_VERSION_NUMBER),
            "ecu_manufacturing_date": hex(IDENTIFIER_SYSTEM_SUPPLIER_ECU_MANUFACTURING_DATE),
            "ecu_part_number": hex(IDENTIFIER_SYSTEM_SUPPLIER_ECU_CODING_CONFIGURATION_PART_NUMBER),
        },
        "Engine_Identifiers": {
            "engine_rpm": hex(IDENTIFIER_ENGINE_RPM),
            "coolant_temperature": hex(IDENTIFIER_ENGINE_COOLANT_TEMPERATURE),
            "throttle_position": hex(IDENTIFIER_THROTTLE_POSITION),
            "vehicle_speed": hex(IDENTIFIER_VEHICLE_SPEED),
            "engine_load": hex(IDENTIFIER_ENGINE_LOAD),
            "fuel_level": hex(IDENTIFIER_FUEL_LEVEL),
            "oil_temperature": hex(IDENTIFIER_OIL_TEMPERATURE),
            "fuel_pressure": hex(IDENTIFIER_FUEL_PRESSURE),
            "intake_air_temperature": hex(IDENTIFIER_ENGINE_AIR_INTAKE),
            # "maf_sensor": hex(IDENTIFIER_MASS_AIR_FLOW_MAF_SENSOR),
            # "ambient_air_temperature": hex(IDENTIFIER_AMBIENT_AIR_TEMPERATURE),
            # "power_output": hex(IDENTIFIER_ENGINE_POWER_OUTPUT),
            # "weight": hex(IDENTIFIER_ENGINE_WEIGHT),
            # "fuel_consumption": hex(IDENTIFIER_ENGINE_FUEL_CONSUMPTION),
            # "torque": hex(IDENTIFIER_ENGINE_TORQUE),
            # "fuel_used": hex(IDENTIFIER_ENGINE_FUEL_USED),
            # "state_of_running": hex(IDENTIFIER_ENGINE_STATE_OF_RUNNING),
            # "current_speed": hex(IDENTIFIER_ENGINE_CURRENT_SPEED),
            # "engine_state": hex(IDENTIFIER_ENGINE_STATE),
            # "serial_number": hex(IDENTIFIER_ENGINE_SERIAL_NUMBER)
        },
        "Battery_Identifiers": {
            "battery_level": hex(IDENTIFIER_BATTERY_ENERGY_LEVEL),
            "voltage": hex(IDENTIFIER_BATTERY_VOLTAGE),
            "percentage": hex(IDENTIFIER_BATTERY_PERCENTAGE),
            "state_of_charge": hex(IDENTIFIER_BATTERY_STATE_OF_CHARGE),
            # "temperature": IDENTIFIER_BATTERY_TEMPERATURE,
            # "life_cycle": IDENTIFIER_BATTERY_LIFE_CYCLE,
            # "fully_charged": IDENTIFIER_BATTERY_FULLY_CHARGED,
            # "range": IDENTIFIER_BATTERY_RANGE,
            # "charging_time": IDENTIFIER_BATTERY_CHARGING_TIME,
            # "device_consumption": IDENTIFIER_DEVICE_CONSUMPTION
        },
        "Doors_Identifiers": {
            "door": hex(IDENTIFIER_DOOR_STATUS),
            "passenger": hex(IDENTIFIER_PASSENGER_DOOR_STATUS),
            "passenger_lock": hex (IDENTIFIER_PASSENGER_DOOR_LOCKED_STATUS),
            "driver": hex (IDENTIFIER_DRIVER_DOOR_STATUS),
            "ajar": hex (IDENTIFIER_AJAR_STATUS)
            # "door": hex(IDENTIFIER_DOOR),
            # "door_serial_number": hex(IDENTIFIER_DOOR_SERIALNUMBER),
            # "lighter_voltage": hex(IDENTIFIER_LIGHTER_VOLTAGE),
            # "light_state": hex(IDENTIFIER_LIGHT_STATE),
            # "belt_state": hex(IDENTIFIER_BELT_STATE),
            # "windows_closed": hex(IDENTIFIER_WINDOWS_CLOSED)
        },
        "HVAC_Identifiers": {
        "mass_air_flow": hex(IDENTIFIER_MASS_AIR_FLOW_MAF_SENSOR), 
        "ambient_air_temperature": hex(IDENTIFIER_AMBIENT_AIR_TEMPERATURE),  
        "cabin_temperature": hex(IDENTIFIER_CABIN_TEMPERATURE),  
        "cabin_temperature_driver_set": hex(IDENTIFIER_CABIN_TEMPERATURE_DRIVER_SET),  
        "fan_speed": hex(IDENTIFIER_FAN_SPEED),  
        "hvac_modes": hex(IDENTIFIER_HVAC_MODES),  
    }
    }
