name: build_checker

on:
  pull_request:
    branches:
      - feature/Backend
      - feature/Frontend
      - feature/Android
      - DEV_Backend
      - DEV_Frontend
      - DEV_Mobile
      - development

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to another environment if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Fetches the code from the repository

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get install -y build-essential cmake libspdlog-dev libfmt-dev libzip-dev python3.8 python3.8-dev python3.8-distutils pybind11-dev # Install essential build tools and libraries

      - name: Run Makefile in src/mcu
        run: |
          cd src/mcu
          make

      - name: Run Makefile in src/ecu_simulation/BatteryModule
        run: |
          cd src/ecu_simulation/BatteryModule
          make

      - name: Run Makefile in src/ecu_simulation/DoorsModule
        run: |
          cd src/ecu_simulation/DoorsModule
          make

      - name: Run Makefile in src/ecu_simulation/EngineModule
        run: |
          cd src/ecu_simulation/EngineModule
          make

      - name: Run Makefile in src/ecu_simulation/HVACModule
        run: |
          cd src/ecu_simulation/HVACModule
          make

      - name: Check Build Results
        run: |
          if [ $? -ne 0 ]; then
            echo "Build failed!"
            exit 1  # Exit with error code to fail the job
          fi
          echo "Build succeeded!"