name: CI

on:
  pull_request:
    branches:
      - DEV_BE  # This workflow will run for pull requests targeting the `DEV_BE` branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to another environment if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Make
        run: sudo apt-get install -y build-essential  # Install essential build tools

      - name: Run Makefile in src/mcu
        run: |
          cd src/mcu
          make  # Run the `make` command
        continue-on-error: true  # Ensure the workflow continues even if this step fails

      - name: Run Makefile in src/ecu_simulation/BatteryModule
        run: |
          cd src/ecu_simulation/BatteryModule
          make  # Run the `make` command
        continue-on-error: true  # Ensure the workflow continues even if this step fails

      - name: Notify of Results
        run: |
          if [ $? -ne 0 ]; then
            echo "Build failed!"
            exit 1  # Exit with error code to fail the job
          fi
          echo "Build succeeded!"
