name: build_checker

on:
  pull_request:
    branches:
      - feature/Backend
      - feature/Frontend
      - feature/Android
      - DEV_Backend
      - DEV_Frontend
      - DEV_Mobile
      - development

jobs:
  mcu_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Checkout MCU submodule to specific branch
        run: |
          cd src/backend/mcu
          git checkout development
          git pull origin development

      - name: Cache APT Dependencies
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-cache
          restore-keys: |
            ${{ runner.os }}-apt-cache

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get install -y build-essential cmake libspdlog-dev libfmt-dev libzip-dev python3.8 python3.8-dev python3.8-distutils pybind11-dev

      - name: Build MCU
        run: |
          make

      - name: Upload MCU Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mcu_build
          path: src/backend/mcu/build  # Adjust path if needed

  battery_module_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache APT Dependencies
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-cache
          restore-keys: |
            ${{ runner.os }}-apt-cache

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get install -y build-essential cmake libspdlog-dev libfmt-dev libzip-dev python3.8 python3.8-dev python3.8-distutils pybind11-dev

      - name: Build Battery Module
        run: |
          cd src/backend/ecu_simulation/BatteryModule
          make

      - name: Upload Battery Module Artifact
        uses: actions/upload-artifact@v3
        with:
          name: battery_module_build
          path: src/backend/ecu_simulation/BatteryModule/build

  doors_module_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache APT Dependencies
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-cache
          restore-keys: |
            ${{ runner.os }}-apt-cache

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get install -y build-essential cmake libspdlog-dev libfmt-dev libzip-dev python3.8 python3.8-dev python3.8-distutils pybind11-dev

      - name: Build Doors Module
        run: |
          cd src/backend/ecu_simulation/DoorsModule
          make

      - name: Upload Doors Module Artifact
        uses: actions/upload-artifact@v3
        with:
          name: doors_module_build
          path: src/backend/ecu_simulation/DoorsModule/build

  engine_module_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache APT Dependencies
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-cache
          restore-keys: |
            ${{ runner.os }}-apt-cache

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get install -y build-essential cmake libspdlog-dev libfmt-dev libzip-dev python3.8 python3.8-dev python3.8-distutils pybind11-dev

      - name: Build Engine Module
        run: |
          cd src/backend/ecu_simulation/EngineModule
          make

      - name: Upload Engine Module Artifact
        uses: actions/upload-artifact@v3
        with:
          name: engine_module_build
          path: src/backend/ecu_simulation/EngineModule/build

  hvac_module_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache APT Dependencies
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-cache
          restore-keys: |
            ${{ runner.os }}-apt-cache

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get install -y build-essential cmake libspdlog-dev libfmt-dev libzip-dev python3.8 python3.8-dev python3.8-distutils pybind11-dev

      - name: Build HVAC Module
        run: |
          cd src/backend/ecu_simulation/HVACModule
          make

      - name: Upload HVAC Module Artifact
        uses: actions/upload-artifact@v3
        with:
          name: hvac_module_build
          path: src/backend/ecu_simulation/HVACModule/build

  finalize:
    runs-on: ubuntu-latest
    needs: [mcu_build, battery_module_build, doors_module_build, engine_module_build, hvac_module_build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Build Results
        run: echo "All modules built successfully."
