name: build_checker

on:
  pull_request:
    branches:
      - feature/OTA  # This workflow will run for pull requests targeting the `feature/OTA` branch
      - feature/UDS  # This workflow will run for pull requests targeting the `feature/UDS` branch
      - DEV_BE  # This workflow will run for pull requests targeting the `DEV_BE` branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to another environment if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Fetches the code from the repository

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get install -y build-essential cmake libspdlog-dev libfmt-dev python3.8-dev # Install essential build tools and libraries
          git clone https://github.com/pybind/pybind11
          cd pybind11
          sudo python3.8 setup.py install
      - name: Run Makefile in src/mcu with Extra Flags
        run: |
          cd src/mcu
          make
      - name: Run Makefile in src/ecu_simulation/BatteryModule with Extra Flags
        run: |
          cd src/ecu_simulation/BatteryModule
          make

      - name: Check Build Results
        run: |
          if [ $? -ne 0 ]; then
            echo "Build failed!"
            exit 1  # Exit with error code to fail the job
          fi
          echo "Build succeeded!"