name: CI

on:
  pull_request:
    branches:
      - DEV_BE  # This workflow will run for pull requests targeting the `DEV_BE` branch
      - feature/UDS  # This workflow will run for pull requests targeting the `feature/UDS` branch
      - feature/OTA  # This workflow will run for pull requests targeting the `feature/OTA` branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to another environment if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Make
        run: sudo apt-get install -y build-essential  # Install essential build tools

      - name: Install spdlog
        run: sudo apt-get install -y libspdlog-dev  # Install spdlog library from the package manager

      - name: Run Makefile in src/mcu
        run: |
          cd src/mcu
          make  # Run the `make` command
        continue-on-error: true  # Ensure the workflow continues even if this step fails

      - name: Run Makefile in src/ecu_simulation/BatteryModule
        run: |
          cd src/ecu_simulation/BatteryModule
          make  # Run the `make` command
        continue-on-error: true  # Ensure the workflow continues even if this step fails
        
      - name: Run Makefile in src/ecu_simulation/EngineModule
      	run: |
      	  cd src/ecu_simulation/EngineModule
      	  make
      	continue-on-error: true
      	
      - name: Run Makefile in src/ecu_simulation/DoorsModule
      	run: |
      	  cd src/ecu_simulation/DoorsModule
      	  make
      	continue-on-error: true
      	
      - name: Run Makefile in src/ecu_simulation/HVACModule
      	run: |
      	  cd src/ecu_simulation/HVACModule
      	  make
      	continue-on-error: true
      	
      - name: Notify of Results
        run: |
          if [ $? -ne 0 ]; then
            echo "Build failed!"
            exit 1  # Exit with error code to fail the job
          fi
          echo "Build succeeded!"
