name: Google C++ Style Analysis
on:
  pull_request:
    branches: [feature/UDS, feature/OTA]
    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', 'meson.build', '**.cmake']
  push:
    branches: [feature/UDS, feature/OTA]
    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', 'meson.build', '**.cmake']
jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Google C++ Style Analysis
        uses: naivesystems/googlecpp-action@2023.3.3.0
#jobs:
#  cpp-linter:
#    runs-on: ubuntu-latest
#    permissions: 
#      pull-requests: write
#    steps:
#      - uses: actions/checkout@v4

      # ... optionally setup build env to create a compilation database

#uses: naivesystems/googlecpp-action@2023.3.3.0
#        id: linter
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          style: ''  # Use .clang-format config file. 
#          tidy-checks: '' # Use .clang-tidy config file. 
          # only 'update' a single comment in a pull request's thread. 
#          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
#          tidy-review: 'true'

 #     - name: Fail fast?!
 #       if: steps.linter.outputs.checks-failed > 0
 #       run: exit 1
